# raw data of one dataset
data_path: ../dataset/kr/FB15K/raw_data
data_loader: FB15KLoader
data_processor: FB15KProcessor

# choose training devices:cpu or 0 or 0,1,2,3
device: 7,6,0,1,2,3

#download data
download: True
download_path: "Research_code/CogKTR/dataset"

# choose the model
model_name: TransE
model_args:
  embedding_dim: 100
  negative_sample_method: Random_Negative_Sampling

# loss function
loss_name: MarginLoss
loss_args:
  margin: 1.0

# metric function
metric_name: Link_Prediction

lr: 0.001
weight_decay: 0.0001

trainer_name: Kr_Trainer
trainer_args:
  trainer_batch_size: 10000
  epoch: 200
  save_step: 10
  metric_step: 20
  save_final_model: 0 # False 
  visualization: 1 # False


