# raw data of one dataset
# data_path: ../dataset/kr/FB15k-237/raw_data
# data_loader: FB15K237Loader
# data_processor: FB15K237Processor
data_path: ../dataset/kr/FB15K/raw_data
data_loader: FB15KLoader
data_processor: FB15KProcessor

#download data
download: True
download_path: "CogKTR/dataset"

# choose training devices:cpu or 0 or 0,1,2,3
device: 0

# choose the model

# #TransE
# model_name: TransE
# model_args:
#   embedding_dim: 100
#   negative_sample_method: Random_Negative_Sampling

# SimplE
# model_name: TuckER
# model_args:
#   dim_entity: 100
#   dim_relation: 100
model_name: TransH
model_args:
  embedding_dim: 50



# loss function
loss_name: MarginLoss
loss_args:
  margin: 0.5
# loss_name: NegLogLikehoodLoss
# loss_args:
#   lamda: None

# metric function
metric_name: Link_Prediction
metric_batch_size: 5000

lr: 0.005
weight_decay: 0.0001

negative_sampler_name: UnifNegativeSampler
# negative_sampler_name: BernNegativeSampler

trainer_name: Kr_Trainer
trainer_args:
  trainer_batch_size: 1200
  epoch: 200
  save_step: None
  metric_step: 5
  save_final_model: 0 # False
  visualization: 1 # False

# #TransR:
# model_name: TransR
# model_args:
#   dim_entity: 100
#   dim_relation: 50
#   negative_sample_method: Random_Negative_Sampling

# # #TransD
# model_name: TransD
# model_args:
#   dim_entity: 200
#   dim_relation: 100
#   negative_sample_method: Random_Negative_Sampling

# # #TransH
# model_name: TransH
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# # TransA
# model_name: TransA
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# #RotatE
# model_name: RotatE
# model_args:
#   embedding_dim: 512
#   negative_sample_method: Random_Negative_Sampling