# raw data of one dataset
data_path: ../dataset/kr/FB15k-237/raw_data
data_loader: FB15K237Loader
data_processor: FB15K237Processor

# choose training devices:cpu or 0 or 0,1,2,3
device: 0,1,2,3

# choose the model
model_name: TransE
model_args:
  embedding_dim: 100
  negative_sample_method: Random_Negative_Sampling

# loss function
loss_name: MarginLoss
loss_args:
  margin: 1.0

# metric function
metric_name: Link_Prediction

lr: 0.001
weight_decay: 0.0001

trainer_name: Kr_Trainer
trainer_args:
  trainer_batch_size: 20000 
  epoch: 100
  save_step: 10
  metric_step: 1
  save_final_model: 0 # False 
  visualization: 1 # False


