data_path: ../dataset/kr/MOBILEWIKIDATA5M/raw_data
data_loader: MOBILEWIKIDATA5MLoader
data_processor: MOBILEWIKIDATA5MProcessor

#download data
download: True
download_path: "Research_code/CogKTR/dataset"

# choose training devices:cpu or 0 or 0,1,2,3
device: 1,3
# choose the model
#KEPLER
model_name: KEPLER
model_args:
  token_length: 5
  embedding_dim: 768  #此参数暂时不可更改，因为采用的Roberta预训练模型的输出维度是768


# loss function
loss_name: KEPLERLoss
loss_args:
  margin: 1.0

# metric function
metric_name: Link_Prediction
metric_batch_size: 500

lr: 0.001
weight_decay: 0.0001

negative_sampler_name: UnifNegativeSampler
# negative_sampler_name: BernNegativeSampler

trainer_name: Kr_Trainer
trainer_args:
  trainer_batch_size: 500
  epoch: 100
  save_step: 2000
  metric_step: 5
  save_final_model: 0 # False
  visualization: 0 # False


########################################################################################################################
# #TransE
#model_name: TransE
#model_args:
#  embedding_dim: 100
#  negative_sample_method: Random_Negative_Sampling


# #TransR:
# model_name: TransR
# model_args:
#   dim_entity: 100
#   dim_relation: 50
#   negative_sample_method: Random_Negative_Sampling

# # #TransD
# model_name: TransD
# model_args:
#   dim_entity: 200
#   dim_relation: 100
#   negative_sample_method: Random_Negative_Sampling

# # #TransH
# model_name: TransH
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# # TransA
# model_name: TransA
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# #RotatE
# model_name: RotatE
# model_args:
#   embedding_dim: 512
#   negative_sample_method: Random_Negative_Sampling

# TuckER
#model_name: TuckER
#model_args:
#  dim_entity: 100
#  dim_relation: 100


# SimPlE
# model_name: SimplE
# model_args:
#   embedding_dim: 100