# raw data of one dataset
#data_path: ../dataset/kr/EVENTKG/raw_data
#data_loader: EVENTKGLoader
#data_processor: EVENTKGProcessor
data_path: ../dataset/kr/FB15K237/raw_data
data_loader: FB15K237Loader
data_processor: FB15K237Processor
#data_path: ../dataset/kr/FB15K/raw_data
#data_loader: FB15KLoader
#data_processor: FB15KProcessor
#download data
download: True
download_path: "Research_code/CogKTR/dataset"

# choose training devices:cpu or 0 or 0,1,2,3
device: 1

# choose the model

# #TransE
# model_name: TransE
# model_args:
#   embedding_dim: 100
#   negative_sample_method: Random_Negative_Sampling

# SimplE
#model_name: TuckER
#model_args:
#  dim_entity: 100
#  dim_relation: 100
model_name: TransE
model_args:
  embedding_dim: 50


# loss function
loss_name: MarginLoss
loss_args:
  margin: 1.0
  C: 0

#loss_name: TuckERLoss
#loss_args:
#  margin: None
# loss_name: NegLogLikehoodLoss
# loss_args:
#   lamda: None

#loss_name: NegSamplingLoss
#loss_args:
#  margin: 3
#  alpha: 0.5
#  neg_per_pos: 10 # 每个正样本对应的负样本个数

# metric function
metric_name: Link_Prediction
metric_args:
  link_prediction_raw: True
  link_prediction_filt: True
  batch_size: 2000000
  reverse: False

lr: 0.001
weight_decay: 0

negative_sampler_name: UnifNegativeSampler
# negative_sampler_name: BernNegativeSampler
#negative_sampler_name: AdversarialSampler


trainer_name: Kr_Trainer
trainer_args:
  trainer_batch_size: 50000
  epoch: 55
  visualization: 1
  apex: True
  dataloaderX: True
  num_workers: 4
  pin_memory: True
  metric_step: 1
  save_step: 100
  metric_final_model: True
  save_final_model: True
  load_checkpoint: "/data/mentianyi/Research_code/CogKTR/dataset/kr/FB15K237/experimental_output/TransE2021-12-17--13-08-01.49--50epochs/checkpoints/TransE_50epochs"



evaluator_name: Kr_Evaluator
evaluator_args:
  evaluator_batch_size: 50000
  dataloaderX: True
  num_workers: 4
  pin_memory: True
#  trained_model_path: "/data/mentianyi/Research_code/CogKTR/dataset/kr/FB15K237/experimental_output/TransE2021-12-17--13-08-01.49--50epochs/checkpoints/TransE_50epochs"

# #TransR:
# model_name: TransR
# model_args:
#   dim_entity: 100
#   dim_relation: 50
#   negative_sample_method: Random_Negative_Sampling

# # #TransD
# model_name: TransD
# model_args:
#   dim_entity: 200
#   dim_relation: 100
#   negative_sample_method: Random_Negative_Sampling

# # #TransH
# model_name: TransH
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# # TransA
# model_name: TransA
# model_args:
#   embedding_dim: 128
#   negative_sample_method: Random_Negative_Sampling

# #RotatE
# model_name: RotatE
# model_args:
#   embedding_dim: 512
#   negative_sample_method: Random_Negative_Sampling